export const SHOWCASE_PROJECTS = [
  {
    _id: 'proj-codecollab-01',
    title: 'CodeCollab — Real-Time Pair Programming IDE',
    description: 'A browser-based collaborative code editor with real-time cursor sharing, embedded terminal, syntax highlighting for 20+ languages, and integrated WebRTC audio calls for peer debugging sessions.',
    tags: ['React', 'Node.js', 'WebSockets', 'MongoDB', 'JavaScript'],
    githubUrl: 'https://github.com/alexjohnson/codecollab',
    liveDemoUrl: 'https://codecollab-demo.vercel.app',
    owner: {
      firebaseUid: 'seed-user-1',
      name: 'Alex Johnson',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    likes: 42,
    likedBy: ['seed-user-2', 'seed-user-3'],
    bookmarkedBy: ['seed-user-2'],
    averageRating: 4.8,
    ratingCount: 18,
    ratings: [
      { userId: 'seed-user-2', value: 5 },
      { userId: 'seed-user-3', value: 5 },
      { userId: 'seed-user-4', value: 4 },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'proj-devpulse-02',
    title: 'DevPulse — AI-Powered Resume & Portfolio Reviewer',
    description: 'An AI assistant that scans student developer GitHub profiles and resumes, extracts skills, calculates ATS readiness score, and provides actionable code quality improvement suggestions.',
    tags: ['Python', 'React', 'AI', 'Node.js', 'TypeScript'],
    githubUrl: 'https://github.com/sarahchen/devpulse-ai',
    liveDemoUrl: 'https://devpulse-ai.preview',
    owner: {
      firebaseUid: 'seed-user-2',
      name: 'Sarah Chen',
      profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    likes: 38,
    likedBy: ['seed-user-1'],
    bookmarkedBy: ['seed-user-1'],
    averageRating: 4.9,
    ratingCount: 24,
    ratings: [
      { userId: 'seed-user-1', value: 5 },
      { userId: 'seed-user-3', value: 5 },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'proj-algoviz-03',
    title: 'AlgoVisualizer — Interactive 3D Algorithm Explorer',
    description: 'Step-by-step 3D visualizations for sorting algorithms, graph traversals (Dijkstra, A*), dynamic programming trees, and binary search trees with adjustable execution speed.',
    tags: ['JavaScript', 'React', 'AI', 'MongoDB'],
    githubUrl: 'https://github.com/marcusv/algo-visualizer',
    liveDemoUrl: 'https://algoviz-3d.vercel.app',
    owner: {
      firebaseUid: 'seed-user-3',
      name: 'Marcus Vance',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    likes: 29,
    likedBy: ['seed-user-1', 'seed-user-2'],
    bookmarkedBy: [],
    averageRating: 4.7,
    ratingCount: 14,
    ratings: [
      { userId: 'seed-user-1', value: 5 },
      { userId: 'seed-user-2', value: 4 },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'proj-campus-04',
    title: 'CampusCart — Student Peer Marketplace & Exchange',
    description: 'A verified campus-only marketplace platform where university students buy, sell, or rent textbooks, electronics, dorm essentials, and exchange study notes with in-app chat.',
    tags: ['React', 'Node.js', 'MongoDB', 'JavaScript'],
    githubUrl: 'https://github.com/priyapatel/campus-cart',
    liveDemoUrl: 'https://campuscart-live.com',
    owner: {
      firebaseUid: 'seed-user-4',
      name: 'Priya Patel',
      profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    },
    likes: 25,
    likedBy: ['seed-user-3'],
    bookmarkedBy: ['seed-user-1'],
    averageRating: 4.6,
    ratingCount: 9,
    ratings: [{ userId: 'seed-user-3', value: 5 }],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'proj-taskflow-05',
    title: 'TaskFlow — Intelligent Kanban & Study Tracker',
    description: 'A productivity app for engineering students with automated Pomodoro timers, GitHub commit tracking integration, task dependency graphing, and weekly velocity charts.',
    tags: ['TypeScript', 'React', 'Node.js', 'MongoDB'],
    githubUrl: 'https://github.com/davidkim/taskflow-pro',
    liveDemoUrl: 'https://taskflow-study.vercel.app',
    owner: {
      firebaseUid: 'seed-user-5',
      name: 'David Kim',
      profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    likes: 31,
    likedBy: ['seed-user-1', 'seed-user-4'],
    bookmarkedBy: ['seed-user-2'],
    averageRating: 4.5,
    ratingCount: 11,
    ratings: [{ userId: 'seed-user-1', value: 4 }],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'proj-neural-06',
    title: 'NeuralPlayground — Deep Learning in the Browser',
    description: 'Train neural networks directly inside your browser with WebGL acceleration. Interactive loss graphs, decision boundary plots, and convolutional filter visualizers.',
    tags: ['Python', 'AI', 'JavaScript', 'React'],
    githubUrl: 'https://github.com/elenar/neural-playground',
    liveDemoUrl: 'https://neuralplayground.app',
    owner: {
      firebaseUid: 'seed-user-6',
      name: 'Elena Rostova',
      profileImage: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    },
    likes: 45,
    likedBy: ['seed-user-2', 'seed-user-5'],
    bookmarkedBy: ['seed-user-3'],
    averageRating: 4.9,
    ratingCount: 21,
    ratings: [{ userId: 'seed-user-2', value: 5 }],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
